CREATE TABLE FIGHTS
(
FIGHTID INT PRIMARY KEY, 
FIGHTER_ID_CHALLANGER fk_fighterID,
FIGHTER_ID_CHALLANGED fk_fighterID, 
CONSTRAINT fk_weightclass FOREIGN KEY (classID) REFERENCES WEIGHT_CLASSES (classID)
WEIGHTCLASS NOT NULL fk_wightclass, 
IS_MAIN BIT NOT NULL,
IS_CO_MAIN BIT NOT NULL,
SCHEDULED ROUNDS TINYINT(1),
CONSTRAINT fk_WINMETH FOREIGN KEY (WINID) REFERENCES WINNING_METHODS (WINID)
WINNING METHOD NOT NULL fk_WINMETH
)
;


CREATE TABLE FIGHTS
(
  FIGHTID               INT PRIMARY KEY,
  FIGHTER_ID_CHALLANGER INT,
  FIGHTER_ID_CHALLANGED INT,
  IS_MAIN               BIT NOT NULL,
  IS_CO_MAIN            BIT NOT NULL,
  SCHEDULED_ROUNDS      TINYINT,
  WEIGHTCLASS           char(3) NOT NULL,
  CLASS_ID              INT NOT NULL,
  WINNING_METHOD        char(3) NOT NULL,
  CONSTRAINT fk_fighterID FOREIGN KEY (FIGHTER_ID_CHALLANGER) REFERENCES FIGHTERS (fighterID),
  CONSTRAINT fk_weightclass FOREIGN KEY (WEIGHTCLASS) REFERENCES WEIGHT_CLASSES (classID),
  CONSTRAINT fk_WINMETH FOREIGN KEY (WINNING_METHOD) REFERENCES WINNING_METHODS (WINID)
);

 